name: Build and publish Java SDK

on:
  workflow_call:
    inputs:
      is-release:
        default: false
        type: boolean
        description: Whether this is a release package ready to be published or not.
    secrets:
      gpg-signing-key:
        required: false
        description: Key to sign the public deliverable.
      gpg-passphrase:
        required: false
        description: Passphrase of the aforementioned GPG signing key.
      ossrh-username:
        required: false
        description: Maven repository username.
      ossrh-token:
        required: false
        description: Maven repository password.

  workflow_dispatch:
    inputs:
      is-release:
        default: false
        type: boolean
        description: Whether this is a release package ready to be published or not.

jobs:
  build-publish-java-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Import GPG key
        if: ${{ inputs.is-release == true }}
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.gpg-signing-key }}
          passphrase: ${{ secrets.gpg-passphrase }}

      - name: Verify GPG key
        if: ${{ inputs.is-release == true }}
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Build project
        run: mvn clean compile

      - name: Share artifacts.
        uses: actions/upload-artifact@v4
        with:
          name: "realitydefender-sdk-java-${{ env.SDK_VERSION }}"
          path: |
            target/
          retention-days: 14
          if-no-files-found: error

      - name: Publish
        if: ${{ inputs.is-release == true }}
        run: mvn clean deploy -P release --batch-mode --no-transfer-progress
        env:
          MAVEN_USERNAME: ${{ secrets.ossrh-username }}
          MAVEN_PASSWORD: ${{ secrets.ossrh-token }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.gpg-passphrase }}


