name: Format, check, and test Java SDK

on:
  workflow_call:
    inputs:
      is-release:
        default: false
        type: boolean
        description: Whether this is a release run or not.
    secrets:
      codecov-token:
        required: true
        description: A token required by Codecov to upload code coverage to their platform.

jobs:
  check-format-test-java-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 21 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Check code formatting
        run: mvn spotless:check

      - name: Run static analysis
        run: mvn compile

      - name: Run tests (non release)
        if: ${{ inputs.is-release == false }}
        run: mvn clean verify -Djacoco.skip=true -Dgpg.skip

      - name: Run tests (release)
        if: ${{ inputs.is-release == true }}
        run: mvn clean verify -Dgpg.skip

      - name: Generate test report
        uses: dorny/test-reporter@v1
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit

      - name: Upload coverage reports to Codecov
        if: matrix.java-version == '11'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.codecov-token }}
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: ${{ inputs.is-release }}
