name: On Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  check-format-test:
    uses: ./.github/workflows/check-format-test.yml
    with:
      is-release: true
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

  build-publish:
    needs: check-format-test
    uses: ./.github/workflows/build-publish.yml
    with:
      is-release: true
    secrets:
      maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven-central-token: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      gpg-key: ${{ secrets.MAVEN_GPG_KEY}}
      gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
